name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.6


flutter:
  assets:
    - assets/images/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo_application.png
  android: true
  ios: true
  web: false
  branding_mode: center
  fullscreen: true