name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  ios : true
  image_path: "assets/images/logo_application.png"

flutter:
  assets:
    - assets/images/